// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: kubearmor.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Health check
type NonceMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         int32                  `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NonceMessage) Reset() {
	*x = NonceMessage{}
	mi := &file_kubearmor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NonceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonceMessage) ProtoMessage() {}

func (x *NonceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kubearmor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonceMessage.ProtoReflect.Descriptor instead.
func (*NonceMessage) Descriptor() ([]byte, []int) {
	return file_kubearmor_proto_rawDescGZIP(), []int{0}
}

func (x *NonceMessage) GetNonce() int32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// message struct
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	UpdatedTime   string                 `protobuf:"bytes,2,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty"`
	ClusterName   string                 `protobuf:"bytes,3,opt,name=ClusterName,proto3" json:"ClusterName,omitempty"`
	HostName      string                 `protobuf:"bytes,4,opt,name=HostName,proto3" json:"HostName,omitempty"`
	HostIP        string                 `protobuf:"bytes,5,opt,name=HostIP,proto3" json:"HostIP,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=Type,proto3" json:"Type,omitempty"`
	Level         string                 `protobuf:"bytes,7,opt,name=Level,proto3" json:"Level,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_kubearmor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_kubearmor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_kubearmor_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *Message) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *Message) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *Message) GetHostIP() string {
	if x != nil {
		return x.HostIP
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// podowner struct
type Podowner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=Ref,proto3" json:"Ref,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Podowner) Reset() {
	*x = Podowner{}
	mi := &file_kubearmor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Podowner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Podowner) ProtoMessage() {}

func (x *Podowner) ProtoReflect() protoreflect.Message {
	mi := &file_kubearmor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Podowner.ProtoReflect.Descriptor instead.
func (*Podowner) Descriptor() ([]byte, []int) {
	return file_kubearmor_proto_rawDescGZIP(), []int{2}
}

func (x *Podowner) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *Podowner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Podowner) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// execevent struct
type ExecEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecID         string                 `protobuf:"bytes,1,opt,name=ExecID,proto3" json:"ExecID,omitempty"`
	ExecutableName string                 `protobuf:"bytes,2,opt,name=ExecutableName,proto3" json:"ExecutableName,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecEvent) Reset() {
	*x = ExecEvent{}
	mi := &file_kubearmor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEvent) ProtoMessage() {}

func (x *ExecEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kubearmor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecEvent.ProtoReflect.Descriptor instead.
func (*ExecEvent) Descriptor() ([]byte, []int) {
	return file_kubearmor_proto_rawDescGZIP(), []int{3}
}

func (x *ExecEvent) GetExecID() string {
	if x != nil {
		return x.ExecID
	}
	return ""
}

func (x *ExecEvent) GetExecutableName() string {
	if x != nil {
		return x.ExecutableName
	}
	return ""
}

// alert struct
type Alert struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Timestamp              int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	UpdatedTime            string                 `protobuf:"bytes,2,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty"`
	ClusterName            string                 `protobuf:"bytes,3,opt,name=ClusterName,proto3" json:"ClusterName,omitempty"`
	HostName               string                 `protobuf:"bytes,4,opt,name=HostName,proto3" json:"HostName,omitempty"`
	NamespaceName          string                 `protobuf:"bytes,5,opt,name=NamespaceName,proto3" json:"NamespaceName,omitempty"`
	Owner                  *Podowner              `protobuf:"bytes,31,opt,name=Owner,proto3" json:"Owner,omitempty"`
	PodName                string                 `protobuf:"bytes,6,opt,name=PodName,proto3" json:"PodName,omitempty"`
	Labels                 string                 `protobuf:"bytes,29,opt,name=Labels,proto3" json:"Labels,omitempty"`
	ContainerID            string                 `protobuf:"bytes,7,opt,name=ContainerID,proto3" json:"ContainerID,omitempty"`
	ContainerName          string                 `protobuf:"bytes,8,opt,name=ContainerName,proto3" json:"ContainerName,omitempty"`
	ContainerImage         string                 `protobuf:"bytes,24,opt,name=ContainerImage,proto3" json:"ContainerImage,omitempty"`
	HostPPID               int32                  `protobuf:"varint,27,opt,name=HostPPID,proto3" json:"HostPPID,omitempty"`
	HostPID                int32                  `protobuf:"varint,9,opt,name=HostPID,proto3" json:"HostPID,omitempty"`
	PPID                   int32                  `protobuf:"varint,10,opt,name=PPID,proto3" json:"PPID,"`
	PID                    int32                  `protobuf:"varint,11,opt,name=PID,proto3" json:"PID,omitempty"`
	UID                    int32                  `protobuf:"varint,12,opt,name=UID,proto3" json:"UID,"`
	ParentProcessName      string                 `protobuf:"bytes,25,opt,name=ParentProcessName,proto3" json:"ParentProcessName,omitempty"`
	ProcessName            string                 `protobuf:"bytes,26,opt,name=ProcessName,proto3" json:"ProcessName,omitempty"`
	PolicyName             string                 `protobuf:"bytes,13,opt,name=PolicyName,proto3" json:"PolicyName,omitempty"`
	Severity               string                 `protobuf:"bytes,14,opt,name=Severity,proto3" json:"Severity,omitempty"`
	Tags                   string                 `protobuf:"bytes,15,opt,name=Tags,proto3" json:"Tags,omitempty"`
	ATags                  []string               `protobuf:"bytes,30,rep,name=ATags,proto3" json:"ATags,omitempty"`
	Message                string                 `protobuf:"bytes,16,opt,name=Message,proto3" json:"Message,omitempty"`
	Type                   string                 `protobuf:"bytes,17,opt,name=Type,proto3" json:"Type,omitempty"`
	Source                 string                 `protobuf:"bytes,18,opt,name=Source,proto3" json:"Source,omitempty"`
	Operation              string                 `protobuf:"bytes,19,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Resource               string                 `protobuf:"bytes,20,opt,name=Resource,proto3" json:"Resource,omitempty"`
	Data                   string                 `protobuf:"bytes,21,opt,name=Data,proto3" json:"Data,omitempty"`
	EventData              map[string]string      `protobuf:"bytes,43,rep,name=EventData,proto3" json:"EventData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Enforcer               string                 `protobuf:"bytes,28,opt,name=Enforcer,proto3" json:"Enforcer,omitempty"`
	Action                 string                 `protobuf:"bytes,22,opt,name=Action,proto3" json:"Action,omitempty"`
	Result                 string                 `protobuf:"bytes,23,opt,name=Result,proto3" json:"Result,omitempty"`
	Cwd                    string                 `protobuf:"bytes,32,opt,name=Cwd,proto3" json:"Cwd,omitempty"`
	TTY                    string                 `protobuf:"bytes,33,opt,name=TTY,proto3" json:"TTY,omitempty"`
	MaxAlertsPerSec        int32                  `protobuf:"varint,34,opt,name=MaxAlertsPerSec,proto3" json:"MaxAlertsPerSec,omitempty"`
	DroppingAlertsInterval int32                  `protobuf:"varint,35,opt,name=DroppingAlertsInterval,proto3" json:"DroppingAlertsInterval,omitempty"`
	ExecEvent              *ExecEvent             `protobuf:"bytes,36,opt,name=ExecEvent,proto3" json:"ExecEvent,omitempty"`
	KubeArmorVersion       string                 `protobuf:"bytes,37,opt,name=KubeArmorVersion,proto3" json:"KubeArmorVersion,omitempty"`
	NodeID                 string                 `protobuf:"bytes,38,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	ProcessHash            string                 `protobuf:"bytes,39,opt,name=ProcessHash,proto3" json:"ProcessHash,omitempty"`
	ParentHash             string                 `protobuf:"bytes,40,opt,name=ParentHash,proto3" json:"ParentHash,omitempty"`
	ResourceHash           string                 `protobuf:"bytes,41,opt,name=ResourceHash,proto3" json:"ResourceHash,omitempty"`
	HashAlgo               string                 `protobuf:"bytes,42,opt,name=HashAlgo,proto3" json:"HashAlgo,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_kubearmor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_kubearmor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_kubearmor_proto_rawDescGZIP(), []int{4}
}

func (x *Alert) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Alert) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *Alert) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *Alert) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *Alert) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *Alert) GetOwner() *Podowner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Alert) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Alert) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *Alert) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *Alert) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Alert) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *Alert) GetHostPPID() int32 {
	if x != nil {
		return x.HostPPID
	}
	return 0
}

func (x *Alert) GetHostPID() int32 {
	if x != nil {
		return x.HostPID
	}
	return 0
}

func (x *Alert) GetPPID() int32 {
	if x != nil {
		return x.PPID
	}
	return 0
}

func (x *Alert) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *Alert) GetUID() int32 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Alert) GetParentProcessName() string {
	if x != nil {
		return x.ParentProcessName
	}
	return ""
}

func (x *Alert) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *Alert) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Alert) GetATags() []string {
	if x != nil {
		return x.ATags
	}
	return nil
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Alert) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Alert) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Alert) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Alert) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Alert) GetEventData() map[string]string {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *Alert) GetEnforcer() string {
	if x != nil {
		return x.Enforcer
	}
	return ""
}

func (x *Alert) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Alert) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Alert) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Alert) GetTTY() string {
	if x != nil {
		return x.TTY
	}
	return ""
}

func (x *Alert) GetMaxAlertsPerSec() int32 {
	if x != nil {
		return x.MaxAlertsPerSec
	}
	return 0
}

func (x *Alert) GetDroppingAlertsInterval() int32 {
	if x != nil {
		return x.DroppingAlertsInterval
	}
	return 0
}

func (x *Alert) GetExecEvent() *ExecEvent {
	if x != nil {
		return x.ExecEvent
	}
	return nil
}

func (x *Alert) GetKubeArmorVersion() string {
	if x != nil {
		return x.KubeArmorVersion
	}
	return ""
}

func (x *Alert) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Alert) GetProcessHash() string {
	if x != nil {
		return x.ProcessHash
	}
	return ""
}

func (x *Alert) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *Alert) GetResourceHash() string {
	if x != nil {
		return x.ResourceHash
	}
	return ""
}

func (x *Alert) GetHashAlgo() string {
	if x != nil {
		return x.HashAlgo
	}
	return ""
}

// log struct
type Log struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         int64                  `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	UpdatedTime       string                 `protobuf:"bytes,2,opt,name=UpdatedTime,proto3" json:"UpdatedTime,omitempty"`
	ClusterName       string                 `protobuf:"bytes,3,opt,name=ClusterName,proto3" json:"ClusterName,omitempty"`
	HostName          string                 `protobuf:"bytes,4,opt,name=HostName,proto3" json:"HostName,omitempty"`
	NamespaceName     string                 `protobuf:"bytes,5,opt,name=NamespaceName,proto3" json:"NamespaceName,omitempty"`
	Owner             *Podowner              `protobuf:"bytes,24,opt,name=Owner,proto3" json:"Owner,omitempty"`
	PodName           string                 `protobuf:"bytes,6,opt,name=PodName,proto3" json:"PodName,omitempty"`
	Labels            string                 `protobuf:"bytes,23,opt,name=Labels,proto3" json:"Labels,omitempty"`
	ContainerID       string                 `protobuf:"bytes,7,opt,name=ContainerID,proto3" json:"ContainerID,omitempty"`
	ContainerName     string                 `protobuf:"bytes,8,opt,name=ContainerName,proto3" json:"ContainerName,omitempty"`
	ContainerImage    string                 `protobuf:"bytes,19,opt,name=ContainerImage,proto3" json:"ContainerImage,omitempty"`
	ParentProcessName string                 `protobuf:"bytes,20,opt,name=ParentProcessName,proto3" json:"ParentProcessName,omitempty"`
	ProcessName       string                 `protobuf:"bytes,21,opt,name=ProcessName,proto3" json:"ProcessName,omitempty"`
	HostPPID          int32                  `protobuf:"varint,22,opt,name=HostPPID,proto3" json:"HostPPID,omitempty"`
	HostPID           int32                  `protobuf:"varint,9,opt,name=HostPID,proto3" json:"HostPID,omitempty"`
	PPID              int32                  `protobuf:"varint,10,opt,name=PPID,proto3" json:"PPID,"`
	PID               int32                  `protobuf:"varint,11,opt,name=PID,proto3" json:"PID,omitempty"`
	UID               int32                  `protobuf:"varint,12,opt,name=UID,proto3" json:"UID,"`
	Type              string                 `protobuf:"bytes,13,opt,name=Type,proto3" json:"Type,omitempty"`
	Source            string                 `protobuf:"bytes,14,opt,name=Source,proto3" json:"Source,omitempty"`
	Operation         string                 `protobuf:"bytes,15,opt,name=Operation,proto3" json:"Operation,omitempty"`
	Resource          string                 `protobuf:"bytes,16,opt,name=Resource,proto3" json:"Resource,omitempty"`
	Data              string                 `protobuf:"bytes,17,opt,name=Data,proto3" json:"Data,omitempty"`
	EventData         map[string]string      `protobuf:"bytes,33,rep,name=EventData,proto3" json:"EventData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Result            string                 `protobuf:"bytes,18,opt,name=Result,proto3" json:"Result,omitempty"`
	Cwd               string                 `protobuf:"bytes,25,opt,name=Cwd,proto3" json:"Cwd,omitempty"`
	TTY               string                 `protobuf:"bytes,26,opt,name=TTY,proto3" json:"TTY,omitempty"`
	ExecEvent         *ExecEvent             `protobuf:"bytes,27,opt,name=ExecEvent,proto3" json:"ExecEvent,omitempty"`
	NodeID            string                 `protobuf:"bytes,28,opt,name=NodeID,proto3" json:"NodeID,omitempty"`
	ProcessHash       string                 `protobuf:"bytes,29,opt,name=ProcessHash,proto3" json:"ProcessHash,omitempty"`
	ParentHash        string                 `protobuf:"bytes,30,opt,name=ParentHash,proto3" json:"ParentHash,omitempty"`
	ResourceHash      string                 `protobuf:"bytes,31,opt,name=ResourceHash,proto3" json:"ResourceHash,omitempty"`
	HashAlgo          string                 `protobuf:"bytes,32,opt,name=HashAlgo,proto3" json:"HashAlgo,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_kubearmor_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_kubearmor_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_kubearmor_proto_rawDescGZIP(), []int{5}
}

func (x *Log) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Log) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *Log) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *Log) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *Log) GetNamespaceName() string {
	if x != nil {
		return x.NamespaceName
	}
	return ""
}

func (x *Log) GetOwner() *Podowner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Log) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Log) GetLabels() string {
	if x != nil {
		return x.Labels
	}
	return ""
}

func (x *Log) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *Log) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *Log) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *Log) GetParentProcessName() string {
	if x != nil {
		return x.ParentProcessName
	}
	return ""
}

func (x *Log) GetProcessName() string {
	if x != nil {
		return x.ProcessName
	}
	return ""
}

func (x *Log) GetHostPPID() int32 {
	if x != nil {
		return x.HostPPID
	}
	return 0
}

func (x *Log) GetHostPID() int32 {
	if x != nil {
		return x.HostPID
	}
	return 0
}

func (x *Log) GetPPID() int32 {
	if x != nil {
		return x.PPID
	}
	return 0
}

func (x *Log) GetPID() int32 {
	if x != nil {
		return x.PID
	}
	return 0
}

func (x *Log) GetUID() int32 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *Log) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Log) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Log) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *Log) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Log) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Log) GetEventData() map[string]string {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *Log) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Log) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *Log) GetTTY() string {
	if x != nil {
		return x.TTY
	}
	return ""
}

func (x *Log) GetExecEvent() *ExecEvent {
	if x != nil {
		return x.ExecEvent
	}
	return nil
}

func (x *Log) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Log) GetProcessHash() string {
	if x != nil {
		return x.ProcessHash
	}
	return ""
}

func (x *Log) GetParentHash() string {
	if x != nil {
		return x.ParentHash
	}
	return ""
}

func (x *Log) GetResourceHash() string {
	if x != nil {
		return x.ResourceHash
	}
	return ""
}

func (x *Log) GetHashAlgo() string {
	if x != nil {
		return x.HashAlgo
	}
	return ""
}

// request message
type RequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        string                 `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_kubearmor_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kubearmor_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_kubearmor_proto_rawDescGZIP(), []int{6}
}

func (x *RequestMessage) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// reply message
type ReplyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Retval        int32                  `protobuf:"varint,1,opt,name=Retval,proto3" json:"Retval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_kubearmor_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kubearmor_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_kubearmor_proto_rawDescGZIP(), []int{7}
}

func (x *ReplyMessage) GetRetval() int32 {
	if x != nil {
		return x.Retval
	}
	return 0
}

// APIEvent represents a captured HTTP/gRPC API call
type APIEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourcePod       string                 `protobuf:"bytes,2,opt,name=source_pod,json=sourcePod,proto3" json:"source_pod,omitempty"`
	SourceNamespace string                 `protobuf:"bytes,3,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	SourceContainer string                 `protobuf:"bytes,4,opt,name=source_container,json=sourceContainer,proto3" json:"source_container,omitempty"`
	DestIp          string                 `protobuf:"bytes,5,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	DestPort        uint32                 `protobuf:"varint,6,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Method          string                 `protobuf:"bytes,7,opt,name=method,proto3" json:"method,omitempty"`                            // HTTP method or gRPC method
	Path            string                 `protobuf:"bytes,8,opt,name=path,proto3" json:"path,omitempty"`                                // HTTP path or gRPC service/method
	StatusCode      int32                  `protobuf:"varint,9,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // HTTP status or gRPC status
	Headers         map[string]string      `protobuf:"bytes,10,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestBody     []byte                 `protobuf:"bytes,11,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseBody    []byte                 `protobuf:"bytes,12,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	Protocol        string                 `protobuf:"bytes,13,opt,name=protocol,proto3" json:"protocol,omitempty"`                     // "HTTP" or "gRPC"
	SocketPtr       uint64                 `protobuf:"varint,14,opt,name=socket_ptr,json=socketPtr,proto3" json:"socket_ptr,omitempty"` // For correlation
	ClusterName     string                 `protobuf:"bytes,15,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	HostName        string                 `protobuf:"bytes,16,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *APIEvent) Reset() {
	*x = APIEvent{}
	mi := &file_kubearmor_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIEvent) ProtoMessage() {}

func (x *APIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_kubearmor_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIEvent.ProtoReflect.Descriptor instead.
func (*APIEvent) Descriptor() ([]byte, []int) {
	return file_kubearmor_proto_rawDescGZIP(), []int{8}
}

func (x *APIEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *APIEvent) GetSourcePod() string {
	if x != nil {
		return x.SourcePod
	}
	return ""
}

func (x *APIEvent) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *APIEvent) GetSourceContainer() string {
	if x != nil {
		return x.SourceContainer
	}
	return ""
}

func (x *APIEvent) GetDestIp() string {
	if x != nil {
		return x.DestIp
	}
	return ""
}

func (x *APIEvent) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *APIEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *APIEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *APIEvent) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *APIEvent) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *APIEvent) GetRequestBody() []byte {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *APIEvent) GetResponseBody() []byte {
	if x != nil {
		return x.ResponseBody
	}
	return nil
}

func (x *APIEvent) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *APIEvent) GetSocketPtr() uint64 {
	if x != nil {
		return x.SocketPtr
	}
	return 0
}

func (x *APIEvent) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *APIEvent) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

// ClientInfo for API observer clients
type ClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	IpAddress     string                 `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_kubearmor_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kubearmor_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_kubearmor_proto_rawDescGZIP(), []int{9}
}

func (x *ClientInfo) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *ClientInfo) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

var File_kubearmor_proto protoreflect.FileDescriptor

const file_kubearmor_proto_rawDesc = "" +
	"\n" +
	"\x0fkubearmor.proto\x12\x06feeder\"$\n" +
	"\fNonceMessage\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x05R\x05nonce\"\xe3\x01\n" +
	"\aMessage\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12 \n" +
	"\vUpdatedTime\x18\x02 \x01(\tR\vUpdatedTime\x12 \n" +
	"\vClusterName\x18\x03 \x01(\tR\vClusterName\x12\x1a\n" +
	"\bHostName\x18\x04 \x01(\tR\bHostName\x12\x16\n" +
	"\x06HostIP\x18\x05 \x01(\tR\x06HostIP\x12\x12\n" +
	"\x04Type\x18\x06 \x01(\tR\x04Type\x12\x14\n" +
	"\x05Level\x18\a \x01(\tR\x05Level\x12\x18\n" +
	"\aMessage\x18\b \x01(\tR\aMessage\"N\n" +
	"\bPodowner\x12\x10\n" +
	"\x03Ref\x18\x01 \x01(\tR\x03Ref\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1c\n" +
	"\tNamespace\x18\x03 \x01(\tR\tNamespace\"K\n" +
	"\tExecEvent\x12\x16\n" +
	"\x06ExecID\x18\x01 \x01(\tR\x06ExecID\x12&\n" +
	"\x0eExecutableName\x18\x02 \x01(\tR\x0eExecutableName\"\xf0\n" +
	"\n" +
	"\x05Alert\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12 \n" +
	"\vUpdatedTime\x18\x02 \x01(\tR\vUpdatedTime\x12 \n" +
	"\vClusterName\x18\x03 \x01(\tR\vClusterName\x12\x1a\n" +
	"\bHostName\x18\x04 \x01(\tR\bHostName\x12$\n" +
	"\rNamespaceName\x18\x05 \x01(\tR\rNamespaceName\x12&\n" +
	"\x05Owner\x18\x1f \x01(\v2\x10.feeder.PodownerR\x05Owner\x12\x18\n" +
	"\aPodName\x18\x06 \x01(\tR\aPodName\x12\x16\n" +
	"\x06Labels\x18\x1d \x01(\tR\x06Labels\x12 \n" +
	"\vContainerID\x18\a \x01(\tR\vContainerID\x12$\n" +
	"\rContainerName\x18\b \x01(\tR\rContainerName\x12&\n" +
	"\x0eContainerImage\x18\x18 \x01(\tR\x0eContainerImage\x12\x1a\n" +
	"\bHostPPID\x18\x1b \x01(\x05R\bHostPPID\x12\x18\n" +
	"\aHostPID\x18\t \x01(\x05R\aHostPID\x12\x12\n" +
	"\x04PPID\x18\n" +
	" \x01(\x05R\x04PPID\x12\x10\n" +
	"\x03PID\x18\v \x01(\x05R\x03PID\x12\x10\n" +
	"\x03UID\x18\f \x01(\x05R\x03UID\x12,\n" +
	"\x11ParentProcessName\x18\x19 \x01(\tR\x11ParentProcessName\x12 \n" +
	"\vProcessName\x18\x1a \x01(\tR\vProcessName\x12\x1e\n" +
	"\n" +
	"PolicyName\x18\r \x01(\tR\n" +
	"PolicyName\x12\x1a\n" +
	"\bSeverity\x18\x0e \x01(\tR\bSeverity\x12\x12\n" +
	"\x04Tags\x18\x0f \x01(\tR\x04Tags\x12\x14\n" +
	"\x05ATags\x18\x1e \x03(\tR\x05ATags\x12\x18\n" +
	"\aMessage\x18\x10 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Type\x18\x11 \x01(\tR\x04Type\x12\x16\n" +
	"\x06Source\x18\x12 \x01(\tR\x06Source\x12\x1c\n" +
	"\tOperation\x18\x13 \x01(\tR\tOperation\x12\x1a\n" +
	"\bResource\x18\x14 \x01(\tR\bResource\x12\x12\n" +
	"\x04Data\x18\x15 \x01(\tR\x04Data\x12:\n" +
	"\tEventData\x18+ \x03(\v2\x1c.feeder.Alert.EventDataEntryR\tEventData\x12\x1a\n" +
	"\bEnforcer\x18\x1c \x01(\tR\bEnforcer\x12\x16\n" +
	"\x06Action\x18\x16 \x01(\tR\x06Action\x12\x16\n" +
	"\x06Result\x18\x17 \x01(\tR\x06Result\x12\x10\n" +
	"\x03Cwd\x18  \x01(\tR\x03Cwd\x12\x10\n" +
	"\x03TTY\x18! \x01(\tR\x03TTY\x12(\n" +
	"\x0fMaxAlertsPerSec\x18\" \x01(\x05R\x0fMaxAlertsPerSec\x126\n" +
	"\x16DroppingAlertsInterval\x18# \x01(\x05R\x16DroppingAlertsInterval\x12/\n" +
	"\tExecEvent\x18$ \x01(\v2\x11.feeder.ExecEventR\tExecEvent\x12*\n" +
	"\x10KubeArmorVersion\x18% \x01(\tR\x10KubeArmorVersion\x12\x16\n" +
	"\x06NodeID\x18& \x01(\tR\x06NodeID\x12 \n" +
	"\vProcessHash\x18' \x01(\tR\vProcessHash\x12\x1e\n" +
	"\n" +
	"ParentHash\x18( \x01(\tR\n" +
	"ParentHash\x12\"\n" +
	"\fResourceHash\x18) \x01(\tR\fResourceHash\x12\x1a\n" +
	"\bHashAlgo\x18* \x01(\tR\bHashAlgo\x1a<\n" +
	"\x0eEventDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\b\n" +
	"\x03Log\x12\x1c\n" +
	"\tTimestamp\x18\x01 \x01(\x03R\tTimestamp\x12 \n" +
	"\vUpdatedTime\x18\x02 \x01(\tR\vUpdatedTime\x12 \n" +
	"\vClusterName\x18\x03 \x01(\tR\vClusterName\x12\x1a\n" +
	"\bHostName\x18\x04 \x01(\tR\bHostName\x12$\n" +
	"\rNamespaceName\x18\x05 \x01(\tR\rNamespaceName\x12&\n" +
	"\x05Owner\x18\x18 \x01(\v2\x10.feeder.PodownerR\x05Owner\x12\x18\n" +
	"\aPodName\x18\x06 \x01(\tR\aPodName\x12\x16\n" +
	"\x06Labels\x18\x17 \x01(\tR\x06Labels\x12 \n" +
	"\vContainerID\x18\a \x01(\tR\vContainerID\x12$\n" +
	"\rContainerName\x18\b \x01(\tR\rContainerName\x12&\n" +
	"\x0eContainerImage\x18\x13 \x01(\tR\x0eContainerImage\x12,\n" +
	"\x11ParentProcessName\x18\x14 \x01(\tR\x11ParentProcessName\x12 \n" +
	"\vProcessName\x18\x15 \x01(\tR\vProcessName\x12\x1a\n" +
	"\bHostPPID\x18\x16 \x01(\x05R\bHostPPID\x12\x18\n" +
	"\aHostPID\x18\t \x01(\x05R\aHostPID\x12\x12\n" +
	"\x04PPID\x18\n" +
	" \x01(\x05R\x04PPID\x12\x10\n" +
	"\x03PID\x18\v \x01(\x05R\x03PID\x12\x10\n" +
	"\x03UID\x18\f \x01(\x05R\x03UID\x12\x12\n" +
	"\x04Type\x18\r \x01(\tR\x04Type\x12\x16\n" +
	"\x06Source\x18\x0e \x01(\tR\x06Source\x12\x1c\n" +
	"\tOperation\x18\x0f \x01(\tR\tOperation\x12\x1a\n" +
	"\bResource\x18\x10 \x01(\tR\bResource\x12\x12\n" +
	"\x04Data\x18\x11 \x01(\tR\x04Data\x128\n" +
	"\tEventData\x18! \x03(\v2\x1a.feeder.Log.EventDataEntryR\tEventData\x12\x16\n" +
	"\x06Result\x18\x12 \x01(\tR\x06Result\x12\x10\n" +
	"\x03Cwd\x18\x19 \x01(\tR\x03Cwd\x12\x10\n" +
	"\x03TTY\x18\x1a \x01(\tR\x03TTY\x12/\n" +
	"\tExecEvent\x18\x1b \x01(\v2\x11.feeder.ExecEventR\tExecEvent\x12\x16\n" +
	"\x06NodeID\x18\x1c \x01(\tR\x06NodeID\x12 \n" +
	"\vProcessHash\x18\x1d \x01(\tR\vProcessHash\x12\x1e\n" +
	"\n" +
	"ParentHash\x18\x1e \x01(\tR\n" +
	"ParentHash\x12\"\n" +
	"\fResourceHash\x18\x1f \x01(\tR\fResourceHash\x12\x1a\n" +
	"\bHashAlgo\x18  \x01(\tR\bHashAlgo\x1a<\n" +
	"\x0eEventDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"(\n" +
	"\x0eRequestMessage\x12\x16\n" +
	"\x06Filter\x18\x01 \x01(\tR\x06Filter\"&\n" +
	"\fReplyMessage\x12\x16\n" +
	"\x06Retval\x18\x01 \x01(\x05R\x06Retval\"\xd8\x04\n" +
	"\bAPIEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"source_pod\x18\x02 \x01(\tR\tsourcePod\x12)\n" +
	"\x10source_namespace\x18\x03 \x01(\tR\x0fsourceNamespace\x12)\n" +
	"\x10source_container\x18\x04 \x01(\tR\x0fsourceContainer\x12\x17\n" +
	"\adest_ip\x18\x05 \x01(\tR\x06destIp\x12\x1b\n" +
	"\tdest_port\x18\x06 \x01(\rR\bdestPort\x12\x16\n" +
	"\x06method\x18\a \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\b \x01(\tR\x04path\x12\x1f\n" +
	"\vstatus_code\x18\t \x01(\x05R\n" +
	"statusCode\x127\n" +
	"\aheaders\x18\n" +
	" \x03(\v2\x1d.feeder.APIEvent.HeadersEntryR\aheaders\x12!\n" +
	"\frequest_body\x18\v \x01(\fR\vrequestBody\x12#\n" +
	"\rresponse_body\x18\f \x01(\fR\fresponseBody\x12\x1a\n" +
	"\bprotocol\x18\r \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"socket_ptr\x18\x0e \x01(\x04R\tsocketPtr\x12!\n" +
	"\fcluster_name\x18\x0f \x01(\tR\vclusterName\x12\x1b\n" +
	"\thost_name\x18\x10 \x01(\tR\bhostName\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"H\n" +
	"\n" +
	"ClientInfo\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress2\xef\x01\n" +
	"\n" +
	"LogService\x129\n" +
	"\vHealthCheck\x12\x14.feeder.NonceMessage\x1a\x14.feeder.ReplyMessage\x12:\n" +
	"\rWatchMessages\x12\x16.feeder.RequestMessage\x1a\x0f.feeder.Message0\x01\x126\n" +
	"\vWatchAlerts\x12\x16.feeder.RequestMessage\x1a\r.feeder.Alert0\x01\x122\n" +
	"\tWatchLogs\x12\x16.feeder.RequestMessage\x1a\v.feeder.Log0\x012D\n" +
	"\vAPIObserver\x125\n" +
	"\vGetAPIEvent\x12\x12.feeder.ClientInfo\x1a\x10.feeder.APIEvent0\x01B)Z'github.com/kubearmor/KubeArmor/protobufb\x06proto3"

var (
	file_kubearmor_proto_rawDescOnce sync.Once
	file_kubearmor_proto_rawDescData []byte
)

func file_kubearmor_proto_rawDescGZIP() []byte {
	file_kubearmor_proto_rawDescOnce.Do(func() {
		file_kubearmor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kubearmor_proto_rawDesc), len(file_kubearmor_proto_rawDesc)))
	})
	return file_kubearmor_proto_rawDescData
}

var file_kubearmor_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_kubearmor_proto_goTypes = []any{
	(*NonceMessage)(nil),   // 0: feeder.NonceMessage
	(*Message)(nil),        // 1: feeder.Message
	(*Podowner)(nil),       // 2: feeder.Podowner
	(*ExecEvent)(nil),      // 3: feeder.ExecEvent
	(*Alert)(nil),          // 4: feeder.Alert
	(*Log)(nil),            // 5: feeder.Log
	(*RequestMessage)(nil), // 6: feeder.RequestMessage
	(*ReplyMessage)(nil),   // 7: feeder.ReplyMessage
	(*APIEvent)(nil),       // 8: feeder.APIEvent
	(*ClientInfo)(nil),     // 9: feeder.ClientInfo
	nil,                    // 10: feeder.Alert.EventDataEntry
	nil,                    // 11: feeder.Log.EventDataEntry
	nil,                    // 12: feeder.APIEvent.HeadersEntry
}
var file_kubearmor_proto_depIdxs = []int32{
	2,  // 0: feeder.Alert.Owner:type_name -> feeder.Podowner
	10, // 1: feeder.Alert.EventData:type_name -> feeder.Alert.EventDataEntry
	3,  // 2: feeder.Alert.ExecEvent:type_name -> feeder.ExecEvent
	2,  // 3: feeder.Log.Owner:type_name -> feeder.Podowner
	11, // 4: feeder.Log.EventData:type_name -> feeder.Log.EventDataEntry
	3,  // 5: feeder.Log.ExecEvent:type_name -> feeder.ExecEvent
	12, // 6: feeder.APIEvent.headers:type_name -> feeder.APIEvent.HeadersEntry
	0,  // 7: feeder.LogService.HealthCheck:input_type -> feeder.NonceMessage
	6,  // 8: feeder.LogService.WatchMessages:input_type -> feeder.RequestMessage
	6,  // 9: feeder.LogService.WatchAlerts:input_type -> feeder.RequestMessage
	6,  // 10: feeder.LogService.WatchLogs:input_type -> feeder.RequestMessage
	9,  // 11: feeder.APIObserver.GetAPIEvent:input_type -> feeder.ClientInfo
	7,  // 12: feeder.LogService.HealthCheck:output_type -> feeder.ReplyMessage
	1,  // 13: feeder.LogService.WatchMessages:output_type -> feeder.Message
	4,  // 14: feeder.LogService.WatchAlerts:output_type -> feeder.Alert
	5,  // 15: feeder.LogService.WatchLogs:output_type -> feeder.Log
	8,  // 16: feeder.APIObserver.GetAPIEvent:output_type -> feeder.APIEvent
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_kubearmor_proto_init() }
func file_kubearmor_proto_init() {
	if File_kubearmor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kubearmor_proto_rawDesc), len(file_kubearmor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_kubearmor_proto_goTypes,
		DependencyIndexes: file_kubearmor_proto_depIdxs,
		MessageInfos:      file_kubearmor_proto_msgTypes,
	}.Build()
	File_kubearmor_proto = out.File
	file_kubearmor_proto_goTypes = nil
	file_kubearmor_proto_depIdxs = nil
}
