apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: block-script
spec:
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  process:
    matchPaths:
    - path: D:\KubeArmor\policies\test-files\malicious.ps1
    - path: D:\KubeArmor\policies\test-files\malicious.bat
  action: Block
