apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: block-dll
spec:
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: "*"
  process:
    matchPaths:
    - path: C:\Users\test\driver\test-files\malicious.dll
    - path: C:\Users\test\driver\test-files\bad.ocx
  action: Block
